[image]
# 保存するファイル名の書式
save_filename_format = "actor%03d.png"

# 画像の組み合わせ
# 一番上のファイルに順に重ねるように画像を貼り付けていく。
pattern = [
# 通常
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/normal.png",
		"test/img/actor019/diff/eyebrows/normal.png",
		"test/img/actor019/diff/mouse/normal.png"
	],
# 会話
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/normal.png",
		"test/img/actor019/diff/eyebrows/normal.png",
		"test/img/actor019/diff/mouse/smile.png"
	],
# 驚き
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/surprise.png",
		"test/img/actor019/diff/eyebrows/normal.png",
		"test/img/actor019/diff/mouse/whisper.png"
	],
# 無表情
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/normal.png",
		"test/img/actor019/diff/eyebrows/normal.png",
		"test/img/actor019/diff/mouse/spin.png"
	],
# 喜
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/smile.png",
		"test/img/actor019/diff/eyebrows/normal.png",
		"test/img/actor019/diff/mouse/smile.png"
	],
# 怒
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/normal.png",
		"test/img/actor019/diff/eyebrows/angry.png",
		"test/img/actor019/diff/mouse/shout.png"
	],
# 哀
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/normal.png",
		"test/img/actor019/diff/eyebrows/sad.png",
		"test/img/actor019/diff/mouse/spin.png"
	],
# 楽
	[
		"test/img/actor019/diff/body/base.png",
		"test/img/actor019/diff/eye/smile.png",
		"test/img/actor019/diff/eyebrows/normal.png",
		"test/img/actor019/diff/mouse/normal.png"
	]
]
